language: csharp
solution: NBug.sln
install:
  - nuget restore NBug.sln
  - nuget install xunit.runners -Version 1.9.0.1566 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NBug.sln
  - mono ./testrunner/xunit.runners.1.9.0.1566/tools/xunit.console.clr4.exe ./NBug.Tests/bin/Release/NBug.Tests.dll
